### ISSUE TITLE
[BUG] Compatibility with svelte based storybooks

### ISSUE THREAD

**Issue by bhvngt** [daimresearch/sb-addon-permutation-table#20]
**Describe the bug**
I was trying this very useful addon on sveltekit based storybook and found it to be crashing. with following errors

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**To Reproduce**
Here's the code sandbox that reproduces this error -

https://codesandbox.io/p/sandbox/blissful-forest-h6wv87?file=%2F.storybook%2Fmain.ts%3A12%2C14

**Expected behavior**
Its a very useful plugin to see all the permutations of variants of the component in one screen. Would love to see it work with svelte.

**Comment by dongyunlee-daim** [comment]
Thank you for bringing this issue! we will look into it.

**Comment by dongyunlee-daim** [comment]
Could you check cs setting once more? this don't working during on install dependencies for some reasons

![스크린샷 2023-06-23 오전 10 07 05](https://github.com/daimresearch/sb-addon-permutation-table/assets/107913240/7076f822-52b1-414b-8bee-b9cd0b732560)

**Comment by bhvngt** [comment]
Thank you for your reply @dongyunlee-daim. Check now [here](https://codesandbox.io/p/sandbox/blissful-forest-h6wv87). I guess there was some issue related to node modules install. I was using `pnpm`. I have switched over to `yarn` and it seems to be working fine now.

**Comment by dongyunlee-daim** [comment]
Ok I'll check this.

**Comment by dongyunlee-daim** [comment]
The bug you reported is occurred for the following reasons.

First, the Invalid hook call error you describe appears to have occurred in the `@storybook/svelte` package. while storybook is made with React, but the inside of the iframe ( preview area) is probably made for each framework they support. however, `sb-addon-permutation-table` calls `useRef` hook of React to detect a user event when the preview area is rendered. I believe this is where the conflict with `@storybook/svelte` is causing the error.

However, Even if this error is fixed, you won’t be able to use this add-on with svelte. Our addon uses a third-party lib called `React-Runner` to interpret components. This library is built for React only, so it can’t interpret svelte code well. Since we left all of code interpretation to this library, this issue will be difficult to fix. Also, as we wrote on README, this addon is designed for React + Typescript project. until now, we don’t have a plan to support other frameworks.

We're closing this issue for the above reasons, and we'll reopen it when we have plans to create our own runner or support other frameworks. Thanks for your interest in the project!
